### ISSUE TITLE
Bytecode heatmap is fun but DUMB

### ISSUE THREAD

**Issue by ExtReMLapin** [WilliamVenner/vscode-glua-enhanced#15]
Bytecode analysis doesn't make sense and it will just confuse the retards who can't understand what is bytecode.
Also it depends of execution context of the said bytecode, bytecode heatmap checks the "cost" of an indidual call to the Instruction and operand, not what it actually does. Right, CALL costs `5` but what about the functions it calls ? You literally cannot know the actual cost of it without having runtime intelligence.
And everything here is when pretending nothing gets ever JIT compiled.

Function A can be faster than function B when both interpreted, but B can be faster then A when both are JIT Compiled.
(see ipairs/pairs performance on Interpreted vs JITed mode)

It literally doesn't make any sense in any of the possible cases.
Sure it's a fun project, but only useful projects needs to be implemented in others projects, not fun ones.

It would be MUCH MUCH better to do static code analysis on code and try to detect design flaws.

Examples : 

* nested player.GetAll loops
* Static rendering code without using render target (iirc it's to save the result of a render) (example, the addon that adds license plates, he re-render the plates on each frames)

**Comment by ExtReMLapin** [comment]
![](https://aws1.discourse-cdn.com/business20/uploads/facepunch1/original/3X/0/7/0708eec1d554290842d59064197730324ca28b46.png)
Just take a look at this, the loop is "less red" than the lines above

**Comment by WilliamVenner** [comment]
Yes you're correct, it mostly is pretty *dumb*, but it was also just for *fun*. I disagree with your view that it shouldn't be included in this project if it's just for fun, because this project can easily actually visualize the data, and doesn't interfere with any other part of the project to achieve that.

1. Inlining the source of function calls could somewhat improve this, it's kind of omegalul but it can help
2. We don't really need to consider JIT in Gmod, since it's highly unlikely your code is going to get JITted anyway due to all the C++ calls
3. This shit is really hidden behind a command, and I would bet money on the fact that most VSCode users, at least using this extension, don't actually know how to open the command input box in the first place. It's for advanced users only, who actually understand some of this shit

Static code analysis would be cool but it's just too broad and not future proof at all, if the bums at gmod actually decide to merge the player.Get* optimizations after all these years then such a static analysis would become invalid.

**Comment by WilliamVenner** [comment]
If anyone does do static code analysis I'm happy to merge it into the project.

**Comment by ExtReMLapin** [comment]
>because this project can easily actually visualize the data, and doesn't interfere with any other part of the project to achieve that.

The issue are the idiots who will download it, and actually thing a loop is takes less time to execute than a table creation.
The same way people use FProfiler without knowing it just flush the JIT cache and is not representative of reality
